In [1]:
! pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.8 MB 5.1 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.8 MB 10.7 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.8 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 14.8 MB/s  0:00:01


In [23]:
import numpy as np

In [ ]:
# numpy leacture 1
# vector -> 1D
# scalar -> 2D


In [ ]:
lst = [1,2,3,4,5,6,7,8,9]
lst2= [1,2,3],[4,5,6],[7,8,9]




[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
arr_2 = np.array(lst2)
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a = np.array([1,3,5,7,9])

In [28]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [30]:
z = np.zeros((3,4))
z.shape

(3, 4)

In [31]:
z_2 = np.zeros(5)
z_2.shape

(5,)

In [32]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(1,5) # these values will be evenly spaced

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [35]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [37]:
np.eye(14)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(10,10)

array([[0.63108951, 0.18837989, 0.09662208, 0.80723301, 0.94556372,
        0.24662561, 0.46930422, 0.08813319, 0.91497915, 0.9177947 ],
       [0.27975221, 0.09827235, 0.7932226 , 0.42924809, 0.80171741,
        0.04293806, 0.28864152, 0.63839328, 0.40854981, 0.14828975],
       [0.32398858, 0.29631918, 0.31290632, 0.49398059, 0.10152303,
        0.8010241 , 0.2717531 , 0.1351613 , 0.27209913, 0.80548139],
       [0.72126332, 0.44729428, 0.3773524 , 0.92490649, 0.46565416,
        0.06527815, 0.1367161 , 0.74016381, 0.93884866, 0.20011618],
       [0.19711729, 0.73579349, 0.07500613, 0.2591415 , 0.83004118,
        0.77080061, 0.1271817 , 0.92154282, 0.92689541, 0.62519599],
       [0.94308754, 0.3044948 , 0.23225263, 0.86413032, 0.94293055,
        0.25535007, 0.59024158, 0.12031096, 0.26996627, 0.54288506],
       [0.64443689, 0.2158826 , 0.40136991, 0.36300017, 0.25988797,
        0.36413293, 0.86710464, 0.52830978, 0.18565866, 0.23294928],
       [0.7239233 , 0.71854521, 0.3019628

In [39]:
np.random.randn(10,10)

array([[-0.7154207 ,  0.76246675, -2.29473915, -1.18845713,  0.01369122,
         1.64709302, -0.56114719, -0.15972103, -1.08502905, -0.64783447],
       [-0.75482502,  0.34531725, -1.35236336,  0.96985962, -2.93116411,
         1.56239348,  0.99839053, -0.12904904, -0.81741717, -0.59006603],
       [-0.06295944,  0.56346584,  0.94229961,  1.26271447, -1.09778281,
        -0.17755824,  1.52881503, -0.16604647, -1.125612  ,  0.13500208],
       [ 0.52739518, -1.8618384 ,  0.73237362, -1.10786283,  1.25889389,
         1.29778009, -0.8720565 , -1.45270953,  0.83102457,  0.55276473],
       [-0.45694584, -1.12727641, -0.33609345,  1.02855455,  1.09973106,
        -0.13551473, -0.28436063,  0.24271251,  0.35161024,  0.60473193],
       [ 0.60067549, -0.40401729,  0.96567783,  0.55456652,  0.59117313,
        -0.30289547, -0.58420206,  0.39266476, -0.26695561, -2.19424492],
       [ 1.47475276, -0.50615351, -1.22691259,  0.70188835,  0.4079377 ,
         1.20156544,  0.31106103,  0.15351818

In [41]:
np.random.randint(10)

3

In [42]:
arr.dtype

dtype('O')

In [44]:
i =np.random.rand(10,10)


In [46]:
i.argmax()

np.int64(95)

In [ ]:
x = int(input("enter a number"))
for i in range(x):
    print('[',end='')
    for j in range(x):
     if i==j:
        print('1 ',end='')
     else:
        print('0 ',end='')
    print(']')    


In [53]:
4%10

4