#Intelligence 
- Abillity to learn from experience.
- it also be defined as the abillity to aquire and apply knowledge.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
##### importing the data set
# iloc define index in dataset

dataset=pd.read_csv("Data.csv")
X = dataset.iloc[:,0:3].values #X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values


In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

"y" includes dependent variable.
"x" icludes independent variable.

In [4]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Taking care of missing Data



In [6]:
! pip install scikit-learn

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [8]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding catagorical data

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

## Encoding the  dependent value

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [12]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])


### Splittng the dataset into training and dataset

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.2,random_state=32)

In [14]:
Y_test

array([1, 1])

feature scalling

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [19]:
X_train

array([[-0.77459667,  1.29099445, -0.57735027, -1.68580983, -1.05553882],
       [-0.77459667,  1.29099445, -0.57735027,  1.53377393,  1.64209282],
       [-0.77459667, -0.77459667,  1.73205081, -0.39797633, -0.40438635],
       [ 1.29099445, -0.77459667, -0.57735027,  0.5678988 ,  0.61885324],
       [-0.77459667,  1.29099445, -0.57735027, -0.07601795, -0.14599252],
       [-0.77459667, -0.77459667,  1.73205081, -0.27277029, -1.24158238],
       [ 1.29099445, -0.77459667, -0.57735027, -0.88091389, -0.68345169],
       [ 1.29099445, -0.77459667, -0.57735027,  1.21181555,  1.2700057 ]])